### ISSUE TITLE
Requiring unknown module "resolveAssetSource"

### ISSUE THREAD

**Issue by rokugou** [Anthonyzou/react-image-zoom#5]
I am using 

```
npm 3.6.0
node v5.7.0
react-native 0.23
```

react-native 0.22 work fine.

**Comment by Anthonyzou** [comment]
I took it out of the next version. Requiring assets wont work anymore though

**Comment by saswn** [comment]
what? :|
Requiring assets wont work anymore
are React Native Idiot ? :|
