### ISSUE TITLE
How to get current zoomScale?

### ISSUE THREAD

**Issue by samuelkraft** [Anthonyzou/react-image-zoom#9]
On iOS we can look for the scrollView `onScroll` event to get current zoomScale. 
How can I get it for for this module on Android?

**Comment by Anthonyzou** [comment]
I add a listener for scale changing. Giving a function to the prop `onScaleChange` will give you something like this. The example has an update.

``` json
{ 
  "focusY": 248.584716796875,
  "focusX": 289.6228942871094,
  "scaleFactor": 1.0006426572799683 
}
```

**Comment by samuelkraft** [comment]
Awesome, thanks!

**Comment by FMCorz** [comment]
For those who are new to this like me, note that the arguments above are found in `e.NativeEvent.scaleFactor`, ...

```
              onScaleChange={(e) => {
                console.log(e.nativeEvent);
              }}/>
```

**Comment by douglasjunior** [comment]
Not work for iOS?
